name = input('Type the name of the character: ').capitalize()
firstGender = input('Gender of character (he / she): ')
secondGender = input('Gender of character (his / her): ')


print('' + firstGender.capitalize() + ' hastened back into the forest. ' + name + ' stood up and trotted along to the right.')
print('Here the beach was interrupted abruptly by the square motif of the landscape;')
print('a great platform of pink granite thrust up uncompromisingly')
print('through forest and terrace and sand and lagoon to make a raised jetty')
print('four feet high. The top of this was covered with a thin layer of soil and')
print('coarse grass and shaded with young palm trees. There was not enough')
print('soil for them to grow to any height and when they reached perhaps')
print('twenty feet they fell and dried, forming a criss-cross pattern of trunks,')
print('very convenient to sit on. The palms that still stood made a green roof,')
print('covered on the underside with a quivering tangle of reflections from the')
print('lagoon. ' + name + ' hauled himself onto this platform, noted the coolness and')
print('shade, shut one eye, and decided that the shadows on ' + secondGender.lower() + ' body were really green.')
print('' + firstGender.capitalize() + ' picked ' + secondGender.lower() + ' way to the seaward edge of the platform and stood looking down into the water.') 
print('It was clear to the bottom and bright the efflorescence of tropical weed and coral.')
print('A school of tiny, glittering fish flicked hither and thither.')
print('' + name + ' spoke to himself, sounding the bass strings of delight.')
